python:
  - "2.7"

env:
  - LUA="luajit"

install:
  - sudo pip install autobahntestsuite
  - sudo apt-get install libev-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luacov-coveralls
  - sudo luarocks install busted 1.11.1-1

script: "sudo luarocks make rockspecs/lua-websockets-scm-1.rockspec && ./test.sh"

after_success:
  - luacov-coveralls
