python:
  - "2.7"

env:
  - LUA="" LUAWS_WSTEST_PORT=8091 LUAWS_SERVER_EV_PORT=8092 LUAWS_SERVER_COPAS_PORT=8093
  - LUA="luajit" LUAWS_WSTEST_PORT=8081 LUAWS_SERVER_EV_PORT=8082 LUAWS_SERVER_COPAS_PORT=8083

before_install:
  - sudo pip install autobahntestsuite
  - sudo apt-get install libev-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install luabitop
  - sudo luarocks install luasocket
  - sudo luarocks install copas
  - sudo luarocks install lua-ev
  - sudo luarocks install lpack
  - git clone git://github.com/lipp/busted.git
  - cd busted
  - sudo luarocks make
  - cd ../

script: "./test.sh"

